# Site settings
title: Corrado Maurini
baseurl: "http://www.lmm.jussieu.fr/~corrado/_site"
url: "http://www.lmm.jussieu.fr/corrado/_site"

# Build settings

github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: UA-2684436-1
disqus_shortname: cmaurini



# jekyll/scholar config (see https://github.com/inukshuk/jekyll-scholar)
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll/scholar

mathjax: true

scholar:
  style: apa
  sort_by: year
  order: descending
  group_by: none
  group_order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: ""

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true

  details_dir:    bibliography
  details_layout: nodetails.html
  details_link:   Details

  bibliography_template: bib
  source: ./_bibliography

#   details_link: "details"
#   details_dir:  "bibliography"
#  details_layout: "details.html"
#  repository: "/pdfs/"



